[package]
name = "bit-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
bit-emission = { path = "../bit-emission" }
bit-staking = { path = "../bit-staking" }
bit-state = { path = "../bit-state" }
bit-transaction = { path = "../bit-transaction" }
ics23 = "0.12.0"
prost = "0.13.5"
tendermint-abci = { version = "=0.40.4", features = ["client"] }
tendermint-proto = "=0.40.4"
thiserror = "1.0.63"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "sync"] }

[dev-dependencies]
bit-types = { path = "../bit-types" }
decaf377 = "0.10.1"
tempfile = "3.10.1"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "sync"] }
